spring:
    application:
        name: user-service
    config:
        import: optional:configserver:http://localhost:8888

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/user-db
        username: root
        password: Quang13102006

    #jpa:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
server:
    port: 8090